### ISSUE TITLE
Any reason to publish ES2015 code?

### ISSUE THREAD

**Issue by sapegin** [woutervh-/timed-memoize#1]
Targed was changes to `es2015` in 89a455173830c3c8a938a0185f0d6bd457b8f7bd, so now UglifyJS fails because of ES6 code. Was it intentional? What was the reason?

**Comment by woutervh-** [comment]
Hi @sapegin, thanks for letting me know it is breaking things somewhere else. I will revert back to ES5 target. The reason I set it originally to ES6 was to generally move forward with the whole javascript-next movement. But I will happily set it back to ES5.

**Comment by sapegin** [comment]
Thanks! This whole movement is quite messy so far ;-)
